POC - Mini Go
AzimMuradov/fp2022-haskell pull request #3
Opened 2022-11-21 22:25 UTC by AzimMuradov

Реализована часть домашнего задания для ранней сдачи.
Присутствует parser, program checker (т.к. предполагается проверять не только типы, но и, например, коллизии имен) и interpreter. Все сделано в рамках ранней сдачи (иначе говоря, отсутствуют некоторые части необходимые для полного решения). Все, что отсутствует, пока помечено `TODO`.
Пока сделаю draft, надо немного почистить и добавить документации.

2022-11-23 10:09 UTC, Kakadu requested changes
Ранняя засчитывается.
В Ast кусоке рантайма затащен --- стрёмно
К НГ осильте монады.

2022-11-23 10:09 UTC, Kakadu commented on Go/app/Main.hs
> +    ]
А там нет какой-нить либы, чтобы руками не парсить?
https://v2.ocaml.org/api/Stdlib.Arg.html

2022-11-23 10:09 UTC, Kakadu commented on Go/app/Main.hs
> +    ]
Выглядит как велосипед

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Ast.hs
> +  deriving (Show)
А там правда нельзя перемешивать объявления?

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Ast.hs
> +  deriving (Show)
Я не уверен, что литерал -- это правильный термин тут.

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Ast.hs
> +  deriving (Show)
Что такое литерал (определение)?

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Errors.hs
> +unreachable' = error "Unreachable!"
Я надеюсь, что в финальной версии использований этой фигни не будет.

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Ast.hs
> +    LitFunction FunctionLiteral
Я не думаю, что литерал тут к месту.

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Ast.hs
> +data Literal
У меня ощущение, что у вас представление рантайм значений сиешалось с Ast.

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +  s <- interpretFunc (Env [Scope funcsScopeMap] []) (funcsMap ! "main") []
!?

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +    funcSelector f = let Ast.FunctionDef id _ = f in id
Короче!

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/ProgramChecker.hs
> +
https://hoogle.haskell.org/
https://hoogle.haskell.org/?hoogle=(Ord%20a)%20%3D%3E%20%5Ba%5D%20-%3E%20Bool

2022-11-23 10:09 UTC, Kakadu commented on Go/mini-go.pest
> +// Rough representation of the grammar
А это что?

2022-11-23 10:09 UTC, Kakadu commented on Go/test-integration/test.sh
> +
Почему автор скрипта не указан?

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +data StmtInterpretationResult = Unit | Ret (Maybe Ast.Value)
В чем разница между Unit и Ref Nothing?

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +data StmtInterpretationResult = Unit | Ret (Maybe Ast.Value)
Ret*

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +
Было бы круто ещё Reader осилить. Хаскель же

2022-11-23 10:09 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +
Или State...

2022-11-23 14:33 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +
А я бы написал все на монадах, но вы же сами сказали, что ими нельзя пользоваться для интерпретации?

2022-11-23 14:35 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +
Вроде бы вы говорили, что это слишком просто или что мы не "проникнемся" функциональным программированием.

2022-11-23 14:37 UTC, AzimMuradov commented on Go/test-integration/test.sh
> +
Я формально просто вдохновился скриптом Вити

2022-11-23 14:38 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +  deriving (Show)
Можно, в AST они разделены для удобства

2022-11-23 14:42 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +  s <- interpretFunc (Env [Scope funcsScopeMap] []) (funcsMap ! "main") []
Нет смысла использовать этот оператор т.к. в program checker-е мы это уже проверили.

2022-11-23 14:50 UTC, AzimMuradov commented on Go/lib/Errors.hs
> +unreachable' = error "Unreachable!"
`unreachable` используется только в тех случаях, когда мы закрываем случаи, которые были до этого проверены, например, checker-ом. Иначе говоря, в checker-е мы проверили, что типы сходятся, поэтому нет смысла аккуратно разбираться с ними в интерпретаторе.

2022-11-23 14:50 UTC, AzimMuradov commented on Go/app/Main.hs
> +    ]
Спасибо, поищу

2022-11-23 15:05 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +    LitFunction FunctionLiteral
Литерал функции или литерал в целом?

2022-11-23 19:31 UTC, Kakadu commented on Go/lib/Ast.hs
> +  deriving (Show)
Порядок может оказаться важен.

2022-11-23 19:32 UTC, Kakadu commented on Go/lib/Errors.hs
> +unreachable' = error "Unreachable!"
КОСТЫЛИ

2022-11-23 19:32 UTC, Kakadu commented on Go/lib/Ast.hs
> +    LitFunction FunctionLiteral
фугкции

2022-11-23 19:32 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +  s <- interpretFunc (Env [Scope funcsScopeMap] []) (funcsMap ! "main") []
КОСТЫЛИ

2022-11-23 19:34 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +
Чего?

2022-11-23 19:34 UTC, Kakadu commented on Go/lib/Interpreter.hs
> +
Я такое про парсер генераторы говорил

2022-11-23 20:27 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +    LitFunction FunctionLiteral
https://go.dev/doc/go1.17_spec#Function_literals

2022-11-24 08:25 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +  deriving (Show)
Парсер соберет их в том же порядке, что и в коде.

```go
func foo() { ... }
var a = ...
func bar() { ... }
var b = ...
```

```
[a, b], [foo, bar]
```

Важен только порядок объявления переменных, и он соблюдается.

2022-11-24 08:31 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +  deriving (Show)
```go
package main

import "fmt"

var a = bar()

func main() {
	fmt.Println(a)
	fmt.Println(b)
}

func bar() int { b = 42; return 17 }

var b = foo()

func foo() int { return 18 }
```

```
17
42
```

2022-11-24 15:02 UTC, AzimMuradov commented on Go/lib/ProgramChecker.hs
> +
Поправил

2022-11-24 15:03 UTC, AzimMuradov commented on Go/test-integration/test.sh
> +
Поправил

2022-12-26 01:10 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +
Поправил

2022-12-26 01:12 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +data StmtInterpretationResult = Unit | Ret (Maybe Ast.Value)
Это необходимо для short circuit return-а

`Unit` - для обычных statement-ов
`Ret (Maybe Ast.Value)` - для `return` statement-ов

2022-12-26 01:15 UTC, AzimMuradov commented on Go/mini-go.pest
> +// Rough representation of the grammar
Это грамматика моего парсера в терминах [pest](https://pest.rs/).
Я это использовал для прототипирования, а позже подумал, что может быть полезным в качестве документации. На данный момент она немного outdated, что отмечено в README.

2022-12-26 01:15 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +    LitFunction FunctionLiteral
Поправил

2022-12-26 01:15 UTC, AzimMuradov commented on Go/lib/Errors.hs
> +unreachable' = error "Unreachable!"
Поправил

2022-12-26 01:16 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +  deriving (Show)
Поправил

2022-12-26 01:16 UTC, AzimMuradov commented on Go/app/Main.hs
> +    ]
Поправил

2022-12-26 01:17 UTC, AzimMuradov commented
Я еще немного порефакторю код и только потом re-request-ну review.

2022-12-26 01:32 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +  s <- interpretFunc (Env [Scope funcsScopeMap] []) (funcsMap ! "main") []
Поправил

2022-12-26 01:32 UTC, AzimMuradov commented on Go/lib/Ast.hs
> +data Literal
Поправил

2022-12-26 01:32 UTC, AzimMuradov commented on Go/lib/Interpreter.hs
> +    funcSelector f = let Ast.FunctionDef id _ = f in id
Поправил

2022-12-27 11:27 UTC, Kakadu commented
> Функции (обычные, рекурсивные, замыкания (в том числе с поддержкой присваивания))
Сделайте отдельный тест, показывающий, что всё есть и работает.

2022-12-27 11:30 UTC, Kakadu commented on Go/lib/Analyzer/AnalyzedAst.hs
> +  deriving (Show)
Я думаю, это принято называт lvalue, так что не стоит изобретать новые назваения

2022-12-27 11:47 UTC, Kakadu commented on Go/lib/Analyzer/AnalysisResult.hs
> +    UnexpectedError
По-моему это попахивает костылями. Можно как-то без этого?

2022-12-27 11:49 UTC, Kakadu commented on Go/lib/Analyzer/AnalysisResult.hs
> +    IdentifierNotFound
А тут хотелось бы видеть какой именно идентификатор. Добавьте параметр, и сделайте тест про это.

2022-12-27 11:50 UTC, Kakadu commented on Go/lib/Analyzer/ConstExpressionConverters.hs
> +  _ -> Left NotConstExpr
Если сворачиватель констант работает, то сделайте какой-нить тест на эту тему, который код печатает упрощенный.

2022-12-27 11:51 UTC, Kakadu commented on Go/lib/Interpreter/InterpretationResult.hs
> +    UnexpectedError
Похоже на костыль, можно без него?

2022-12-27 11:52 UTC, Kakadu commented
Вроде пока есть что подопиливать.

2022-12-27 13:40 UTC, AzimMuradov commented on Go/lib/Analyzer/ConstExpressionConverters.hs
> +  _ -> Left NotConstExpr
А можно ли печатать в тесте и сравнивать analyzed AST? На данный момент у меня отсутствуют возможность восстанавливать программу по его AST.

2022-12-27 13:41 UTC, AzimMuradov commented on Go/lib/Analyzer/ConstExpressionConverters.hs
> +  _ -> Left NotConstExpr
Но на данный момент есть тест, который демонстрирует это со сверхбольшими константами

2022-12-28 00:12 UTC, AzimMuradov commented on Go/lib/Analyzer/AnalyzedAst.hs
> +  deriving (Show)
Поправил

2022-12-28 00:12 UTC, AzimMuradov commented on Go/lib/Analyzer/AnalysisResult.hs
> +    UnexpectedError
Поправил

2022-12-28 00:54 UTC, AzimMuradov commented on Go/lib/Analyzer/AnalysisResult.hs
> +    IdentifierNotFound
Поправил

2022-12-28 10:43 UTC, Kakadu commented on Go/lib/Analyzer/ConstExpressionConverters.hs
> +  _ -> Left NotConstExpr
Я забыл, что такое  analyzed AST

2022-12-28 15:39 UTC, AzimMuradov commented on Go/lib/Analyzer/ConstExpressionConverters.hs
> +  _ -> Left NotConstExpr
Это AST, которое производит analyzer после своей работы. Там уже стерты типы и произведены все упрощения, которые поддерживаются в программе. В Analyzed AST сворачиватель констант уже отработал.

2022-12-28 22:47 UTC, AzimMuradov commented on Go/lib/Interpreter/InterpretationResult.hs
> +    UnexpectedError
Это не костыль, это `unreachable`

2022-12-29 18:13 UTC, Kakadu commented on Go/lib/Analyzer/ConstExpressionConverters.hs
> +  _ -> Left NotConstExpr
Тогда можно печатать упрощенный AST

2023-01-03 19:36 UTC, AzimMuradov commented
> > Функции (обычные, рекурсивные, замыкания (в том числе с поддержкой присваивания))
> 
> Сделайте отдельный тест, показывающий, что всё есть и работает. А то я не нашел

Сделал

2023-01-03 19:39 UTC, AzimMuradov commented
Вроде все допилил, но не хватает тестов, в том числе демонстрации `AnanlyzedAst` как Вы просили.

2023-01-03 19:42 UTC, AzimMuradov commented
Я еще обещал haddock подсоединить, но это чутка позже (но постараюсь до 7).

2023-01-03 21:14 UTC, Kakadu commented
А если в мутабельные переменные класть замыкания, оно тоже работает?

2023-01-03 21:16 UTC, AzimMuradov commented
> А если в мутабельные переменные класть замыкания, оно тоже работает?

Не совсем понял вопрос, у меня все переменные мутабельные)

2023-01-03 21:21 UTC, Kakadu commented
> > А если в мутабельные переменные класть замыкания, оно тоже работает?
> 
> Не совсем понял вопрос, у меня все переменные мутабельные)

Ну я могу в одной функции построить замыкание, сложить в глобальную переменную и вызвать потом? Сделайте тест какой-нить про это

2023-01-04 09:40 UTC, Kakadu approved these changes

2023-01-04 09:41 UTC, merged