FSharp with Units of Measure | Alexander Zadorozhnyy
AzimMuradov/fp2022-haskell pull request #4
Opened 2023-01-08 22:41 UTC by Alexander-Zadorozhnyy

2023-01-09 22:17 UTC, Kakadu commented on FSharpUoM/lib/Interpreter/Interpreter.hs
> +    replaceBody :: Identifier -> Expr -> [Expr] -> State [Bool] [Expr]
А что это за список булов?

2023-01-09 22:21 UTC, Alexander-Zadorozhnyy commented on FSharpUoM/lib/Interpreter/Interpreter.hs
> +    replaceBody :: Identifier -> Expr -> [Expr] -> State [Bool] [Expr]
Это по сути стек структура, с помощью которой мы понимаем можно ли заменять identifier в данной части программы или нет, т.е если у нас есть fun x y z -> ... let x = 7 in ... мы не можем внутри let заменять x на значение переданное выше. Заменять мы можем только если все false.

2023-01-09 22:24 UTC, Kakadu commented on FSharpUoM/lib/TypeInference/HindleyMilner.hs
> +
Вы хоть представляете, что значат все эти слова выше?)

2023-01-09 22:30 UTC, Kakadu requested changes

2023-01-09 22:30 UTC, Kakadu commented on FSharpUoM/test-integration/tests/fix.out
> +val fix: forall a2 a3. (a2 -> a3) -> a3
Тип неправильный, не?

2023-01-09 22:32 UTC, Alexander-Zadorozhnyy commented on FSharpUoM/lib/TypeInference/HindleyMilner.hs
> +
Если вы про pattern - то это просто синонимы шаблонов, которые позволяют нам легче работать с Type и UType так же, как если бы они были просто рекурсивными типами. Сделано, просто чтобы не нужно было везде писать Fix и UTerm. А данные слова Fix и UTerm предоставляются библиотекой unification-fd соответственно для работы с унификацией.

2023-01-09 22:34 UTC, Alexander-Zadorozhnyy commented on FSharpUoM/test-integration/tests/fix.out
> +val fix: forall a2 a3. (a2 -> a3) -> a3
Как только данной функции предоставится тип хотя бы одного аргумента, то он сразу же станет 'a -> 'a -> 'a. Дальше все работает верно и везде все корректно определяется.

2023-01-10 07:52 UTC, Kakadu commented on FSharpUoM/test-integration/tests/fix.out
> +val fix: forall a2 a3. (a2 -> a3) -> a3
Но прямо сейчас -- неверно

2023-01-11 11:41 UTC, Kakadu commented
У вас ещё occurs check нет, что расходится с F#

2023-01-11 11:49 UTC, Alexander-Zadorozhnyy commented
А вы не могли бы уточнить, что под этим подразумевается? Из того, что я нашел в интернете --- это проверка на бесконечные типы, если я правильно понял?

2023-01-11 11:52 UTC, Kakadu commented
Я это на лекциях, вообще-то рассказывал

2023-01-11 11:56 UTC, Kakadu commented
```
> let recc  foo x = foo x;;
val c: forall a2 a3. (a2 -> a3) -> a2 -> a3
```
Я думаю, вот это тоже не правильно.

2023-01-11 12:05 UTC, merged